# Generated by Django 5.2 on 2025-05-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('admin', 'Admin'), ('writer', 'Writer')], default='reader', max_length=20),
        ),
    ]
